version: "3.4"

services:
    poste:
        image: analogic/post.io
        restart: alaways
        network_mode: "host"
        volumes:
            - /rootmail-data/:/data
        environment: 
            - HTTPS=ON